# Generated by Django 5.2.16 on 2026-08-14 12:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0003_severity_keyword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('representative_location', django.contrib.gis.db.models.fields.PointField(geography=True, spatial_index=False, srid=4326)),
                ('computed_severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=16)),
                ('computed_severity_rationale', models.TextField()),
                ('overridden_severity', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=16, null=True)),
                ('severity_override_reason', models.TextField(blank=True)),
                ('severity_overridden_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('triaged', 'Triaged'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('insufficient_info', 'Insufficient information'), ('hidden', 'Hidden by moderation'), ('removed', 'Removed by moderation')], db_index=True, default='submitted', max_length=24)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicates', to='issues.issue')),
                ('primary_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='classification.category')),
                ('severity_overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='severity_overridden_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'issue',
                'verbose_name_plural': 'issues',
                'db_table': 'issues_issue',
                'ordering': ['opened_at'],
                'indexes': [models.Index(fields=['primary_category', 'status', 'opened_at'], name='issues_issue_queue_idx')],
            },
        ),
    ]
