# Generated by Django 5.2.16 on 2026-08-14 12:48

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    # PostgreSQL forbids CREATE/DROP INDEX CONCURRENTLY inside a transaction.
    atomic = False

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        # GeoDjango 5.2's spatial-index SQL builder drops the `concurrently=True` argument used by
        # AddIndexConcurrently. Keep Django's model state and execute the required SQL explicitly.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX CONCURRENTLY "issues_issue_location_gist" '
                        'ON "issues_issue" USING GIST ("representative_location")'
                    ),
                    reverse_sql=(
                        'DROP INDEX CONCURRENTLY IF EXISTS "issues_issue_location_gist"'
                    ),
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="issue",
                    index=django.contrib.postgres.indexes.GistIndex(
                        fields=["representative_location"],
                        name="issues_issue_location_gist",
                    ),
                ),
            ],
        ),
    ]
