# Generated by Django 5.2.16 on 2026-08-14 13:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
from typing import Any


# Chosen conservative starting configuration. The product docs deliberately leave tuning open;
# API §6.10 provides 50 m / 72 h as the concrete example, and Architecture §4.3 prefers
# under-merging over over-merging. These rows are data and remain Admin-editable after deployment.
DEFAULT_RADIUS_M = 50
DEFAULT_TIME_WINDOW_HOURS = 72


def seed_clustering_rules(apps: Any, schema_editor: Any) -> None:
    """Give every controlled taxonomy category one active starting rule."""
    Category = apps.get_model("classification", "Category")
    ClusteringRule = apps.get_model("issues", "ClusteringRule")
    ClusteringRule.objects.bulk_create(
        [
            ClusteringRule(
                category=category,
                radius_m=DEFAULT_RADIUS_M,
                time_window_hours=DEFAULT_TIME_WINDOW_HOURS,
                status="active",
            )
            for category in Category.objects.all()
        ]
    )


def unseed_clustering_rules(apps: Any, schema_editor: Any) -> None:
    """Remove only the unchanged seed rows when reversing this migration."""
    ClusteringRule = apps.get_model("issues", "ClusteringRule")
    ClusteringRule.objects.filter(
        radius_m=DEFAULT_RADIUS_M,
        time_window_hours=DEFAULT_TIME_WINDOW_HOURS,
        status="active",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_severity_keyword'),
        ('issues', '0002_issue_issues_issue_location_gist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius_m', models.PositiveIntegerField(help_text='Maximum distance in metres for joining an existing Issue.', validators=[django.core.validators.MinValueValidator(1)])),
                ('time_window_hours', models.PositiveIntegerField(help_text='Maximum Issue age in hours for accepting another Report.', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], db_index=True, default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clustering_rules', to='classification.category')),
            ],
            options={
                'verbose_name': 'clustering rule',
                'verbose_name_plural': 'clustering rules',
                'db_table': 'issues_clustering_rule',
                'ordering': ['category_id', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('radius_m__gt', 0)), name='issues_rule_radius_positive'), models.CheckConstraint(condition=models.Q(('time_window_hours__gt', 0)), name='issues_rule_window_positive'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('category',), name='issues_rule_one_active_category')],
            },
        ),
        migrations.RunPython(seed_clustering_rules, unseed_clustering_rules),
    ]
