# Generated by Django 5.2.16 on 2026-08-14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0004_authority_two_factor"),
        ("issues", "0003_clusteringrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Confirmation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmations",
                        to="issues.issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "confirmation",
                "verbose_name_plural": "confirmations",
                "db_table": "issues_confirmation",
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issue", "citizen"),
                        name="issues_confirmation_one_per_citizen",
                    )
                ],
            },
        ),
    ]
