# Generated by Django 5.2.16 on 2026-08-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_confirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="reopened_from",
            field=models.OneToOneField(
                blank=True,
                help_text="The historical resolved/closed Issue this recurrence reopens.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reopened_as",
                to="issues.issue",
            ),
        ),
    ]
