# Generated by Django 5.2.16 on 2026-08-14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


IMMUTABLE_TRIGGER = "issues_status_event_immutable"
IMMUTABLE_FUNCTION = "issues_status_event_immutable_fn"


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0005_issue_reopened_from"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_status", models.CharField(choices=[
                    ("submitted", "Submitted"), ("triaged", "Triaged"),
                    ("acknowledged", "Acknowledged"), ("in_progress", "In progress"),
                    ("resolved", "Resolved"), ("closed", "Closed"),
                    ("rejected", "Rejected"), ("duplicate", "Duplicate"),
                    ("insufficient_info", "Insufficient information"),
                    ("hidden", "Hidden by moderation"), ("removed", "Removed by moderation"),
                ], max_length=24)),
                ("to_status", models.CharField(choices=[
                    ("submitted", "Submitted"), ("triaged", "Triaged"),
                    ("acknowledged", "Acknowledged"), ("in_progress", "In progress"),
                    ("resolved", "Resolved"), ("closed", "Closed"),
                    ("rejected", "Rejected"), ("duplicate", "Duplicate"),
                    ("insufficient_info", "Insufficient information"),
                    ("hidden", "Hidden by moderation"), ("removed", "Removed by moderation"),
                    ("reopen", "Reopen"),
                ], max_length=24)),
                ("reason", models.TextField(blank=True)),
                ("public_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                    related_name="status_events", to=settings.AUTH_USER_MODEL)),
                ("issue", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                    related_name="status_events", to="issues.issue")),
                ("related_issue", models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="related_status_events", to="issues.issue")),
            ],
            options={
                "verbose_name": "status event",
                "verbose_name_plural": "status events",
                "db_table": "issues_status_event",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.RunSQL(
            sql=f"""
                CREATE FUNCTION {IMMUTABLE_FUNCTION}() RETURNS trigger
                LANGUAGE plpgsql AS $$
                BEGIN
                    RAISE EXCEPTION 'Status events are immutable';
                END;
                $$;
                CREATE TRIGGER {IMMUTABLE_TRIGGER}
                BEFORE UPDATE OR DELETE ON issues_status_event
                FOR EACH ROW EXECUTE FUNCTION {IMMUTABLE_FUNCTION}();
            """,
            reverse_sql=f"""
                DROP TRIGGER IF EXISTS {IMMUTABLE_TRIGGER} ON issues_status_event;
                DROP FUNCTION IF EXISTS {IMMUTABLE_FUNCTION}();
            """,
        ),
    ]
