# Generated by Django 5.2.16 on 2026-08-07 16:32

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0002_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, spatial_index=False, srid=4326)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], default='en', max_length=8)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing (awaiting classification)'), ('triaged', 'Triaged (attached to an Issue)'), ('hidden', 'Hidden by moderation'), ('removed', 'Removed by moderation')], db_index=True, default='submitted', max_length=16)),
                ('severity_signal', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=16, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('classification_source', models.CharField(blank=True, choices=[('llm', 'Hosted LLM'), ('fallback', 'Keyword fallback'), ('citizen', 'Citizen-supplied at submission'), ('authority', 'Authority re-categorization')], max_length=16, null=True)),
                ('classification_model', models.CharField(blank=True, max_length=100)),
                ('classification_rationale', models.TextField(blank=True)),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='classification.category')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'db_table': 'reporting_report',
                'ordering': ['-created_at'],
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['location'], name='reporting_report_location_gist'), models.Index(fields=['author', '-created_at'], name='reporting_report_author_idx'), models.Index(fields=['status', 'created_at'], name='reporting_report_status_idx')],
            },
        ),
    ]
