# Generated by Django 5.2.16 on 2026-08-14 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        ('reporting', '0002_report_classification_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='issues.issue'),
        ),
    ]
