# Generated by Django 5.2.16 on 2026-08-07 16:32

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # ⚠️ **`identity.0001` is named explicitly because it runs `CreateExtension("postgis")`.**
    # Django orders migrations by the dependency graph, not by app name, and `geo` has no other
    # path to `identity` — it holds no FK to the user model. Without this edge Django is free to
    # apply `geo.0001` first, and `CREATE TABLE ... geography(MultiPolygon,4326)` fails on a
    # database where the extension does not exist yet.
    #
    # ⚠️ The compose database uses the `postgis/postgis` image, which pre-creates the extension —
    # so `migrate` there succeeds either way and proves nothing. Verify ordering on a fresh
    # database holding only `plpgsql` (the A7 procedure).
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='CityBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, help_text='The served city outline. Reports outside it are rejected (BR-35).', spatial_index=False, srid=4326)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this is the currently served boundary. Retire rather than delete.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'city boundary',
                'verbose_name_plural': 'city boundaries',
                'db_table': 'geo_city_boundary',
                'ordering': ['name'],
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['area'], name='geo_city_boundary_area_gist')],
            },
        ),
    ]
