# Generated by Django 5.2.16 on 2026-08-14

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_seed_city_boundary"),
    ]

    operations = [
        migrations.CreateModel(
            name="POI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "poi_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("school", "School"),
                            ("highway", "Highway"),
                            ("market", "Market"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        spatial_index=False,
                        srid=4326,
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "point of interest",
                "verbose_name_plural": "points of interest",
                "db_table": "geo_poi",
                "ordering": ["name", "pk"],
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["location"], name="geo_poi_location_gist"
                    ),
                    models.Index(
                        fields=["poi_type", "is_active"], name="geo_poi_type_active_idx"
                    ),
                ],
            },
        ),
    ]
