CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE django_content_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_label VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    CONSTRAINT django_content_type_app_model_unique UNIQUE (app_label, model)
);
CREATE TABLE identity_user (
    id UUID PRIMARY KEY,
    password VARCHAR(128) NOT NULL,
    last_login TIMESTAMPTZ NULL,
    is_superuser BOOLEAN NOT NULL DEFAULT FALSE,
    email VARCHAR(254) UNIQUE NULL,
    phone VARCHAR(16) UNIQUE NULL,
    email_verified_at TIMESTAMPTZ NULL,
    phone_verified_at TIMESTAMPTZ NULL,
    role VARCHAR(16) NOT NULL DEFAULT 'citizen'
        CHECK (role IN ('citizen', 'authority', 'admin')),
    status VARCHAR(16) NOT NULL DEFAULT 'registered'
        CHECK (status IN ('registered', 'verified', 'active', 'suspended',
                          'deprovisioned', 'deleted')),
    preferred_language VARCHAR(8) NOT NULL DEFAULT 'en'
        CHECK (preferred_language IN ('en', 'bn')),
    require_two_factor BOOLEAN NOT NULL DEFAULT FALSE,
    is_staff BOOLEAN NOT NULL DEFAULT FALSE,
    date_joined TIMESTAMPTZ NOT NULL,
    CONSTRAINT identity_user_has_contact_or_anonymized CHECK (
        email IS NOT NULL OR phone IS NOT NULL OR status = 'deleted'
    )
);
CREATE TABLE identity_verificationcode (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    channel VARCHAR(8) NOT NULL CHECK (channel IN ('email', 'phone')),
    code_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ NULL,
    attempts SMALLINT NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT identity_verificationcode_user_fk
        FOREIGN KEY (user_id) REFERENCES identity_user(id) ON DELETE CASCADE
);
CREATE TABLE classification_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(50) NOT NULL UNIQUE,
    name_en VARCHAR(100) NOT NULL UNIQUE,
    name_bn VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'retired')),
    created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE identity_user_category_scope (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT identity_user_category_scope_unique UNIQUE (user_id, category_id),
    CONSTRAINT identity_user_category_scope_user_fk
        FOREIGN KEY (user_id) REFERENCES identity_user(id) ON DELETE CASCADE,
    CONSTRAINT identity_user_category_scope_category_fk
        FOREIGN KEY (category_id) REFERENCES classification_category(id) ON DELETE CASCADE
);
CREATE TABLE classification_severity_keyword (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term VARCHAR(100) NOT NULL UNIQUE,
    language VARCHAR(8) NOT NULL DEFAULT 'en'
        CHECK (language IN ('en', 'bn')),
    severity VARCHAR(16) NOT NULL
        CHECK (severity IN ('critical', 'high', 'medium', 'low')),
    category_id BIGINT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'retired')),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT classification_keyword_category_fk
        FOREIGN KEY (category_id) REFERENCES classification_category(id) ON DELETE RESTRICT
);
CREATE TABLE issues_clustering_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    radius_m INTEGER NOT NULL CHECK (radius_m > 0),
    time_window_hours INTEGER NOT NULL CHECK (time_window_hours > 0),
    status VARCHAR(16) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'retired')),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT issues_clustering_rule_category_fk
        FOREIGN KEY (category_id) REFERENCES classification_category(id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX issues_rule_one_active_category
    ON issues_clustering_rule(category_id) WHERE status = 'active';
CREATE TABLE geo_city_boundary (
    id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    area GEOGRAPHY(MULTIPOLYGON, 4326) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE geo_poi (
    id UUID PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    poi_type VARCHAR(20) NOT NULL
        CHECK (poi_type IN ('hospital', 'school', 'highway', 'market')),
    location GEOGRAPHY(POINT, 4326) NOT NULL,
    source VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE issues_issue (
    id UUID PRIMARY KEY,
    primary_category_id BIGINT NOT NULL,
    representative_location GEOGRAPHY(POINT, 4326) NOT NULL,
    computed_severity VARCHAR(16) NOT NULL
        CHECK (computed_severity IN ('critical', 'high', 'medium', 'low')),
    computed_severity_rationale TEXT NOT NULL,
    overridden_severity VARCHAR(16) NULL
        CHECK (overridden_severity IS NULL OR
               overridden_severity IN ('critical', 'high', 'medium', 'low')),
    severity_override_reason TEXT NOT NULL DEFAULT '',
    severity_overridden_by_id UUID NULL,
    severity_overridden_at TIMESTAMPTZ NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'submitted'
        CHECK (status IN ('submitted', 'triaged', 'acknowledged', 'in_progress',
                          'resolved', 'closed', 'rejected', 'duplicate',
                          'insufficient_info', 'hidden', 'removed')),
    assignee_id UUID NULL,
    duplicate_of_id UUID NULL,
    reopened_from_id UUID NULL,
    opened_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT issues_issue_category_fk
        FOREIGN KEY (primary_category_id) REFERENCES classification_category(id) ON DELETE RESTRICT,
    CONSTRAINT issues_issue_override_actor_fk
        FOREIGN KEY (severity_overridden_by_id) REFERENCES identity_user(id) ON DELETE RESTRICT,
    CONSTRAINT issues_issue_assignee_fk
        FOREIGN KEY (assignee_id) REFERENCES identity_user(id) ON DELETE RESTRICT,
    CONSTRAINT issues_issue_duplicate_fk
        FOREIGN KEY (duplicate_of_id) REFERENCES issues_issue(id) ON DELETE RESTRICT,
    CONSTRAINT issues_issue_reopened_from_fk
        FOREIGN KEY (reopened_from_id) REFERENCES issues_issue(id) ON DELETE RESTRICT
);
CREATE TABLE reporting_report (
    id UUID PRIMARY KEY,
    author_id UUID NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    category_id BIGINT NULL,
    location GEOGRAPHY(POINT, 4326) NOT NULL,
    address VARCHAR(255) NOT NULL DEFAULT '',
    language VARCHAR(8) NOT NULL DEFAULT 'en'
        CHECK (language IN ('en', 'bn')),
    status VARCHAR(16) NOT NULL DEFAULT 'submitted'
        CHECK (status IN ('submitted', 'processing', 'triaged', 'hidden', 'removed')),
    severity_signal VARCHAR(16) NULL
        CHECK (severity_signal IS NULL OR
               severity_signal IN ('critical', 'high', 'medium', 'low')),
    confidence DOUBLE PRECISION NULL,
    classification_source VARCHAR(16) NULL
        CHECK (classification_source IS NULL OR
               classification_source IN ('llm', 'fallback', 'citizen', 'authority')),
    classification_model VARCHAR(100) NOT NULL DEFAULT '',
    classification_rationale TEXT NOT NULL DEFAULT '',
    classified_at TIMESTAMPTZ NULL,
    classification_needs_review BOOLEAN NOT NULL DEFAULT FALSE,
    issue_id UUID NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT reporting_report_author_fk
        FOREIGN KEY (author_id) REFERENCES identity_user(id) ON DELETE RESTRICT,
    CONSTRAINT reporting_report_category_fk
        FOREIGN KEY (category_id) REFERENCES classification_category(id) ON DELETE RESTRICT,
    CONSTRAINT reporting_report_issue_fk
        FOREIGN KEY (issue_id) REFERENCES issues_issue(id) ON DELETE RESTRICT
);
CREATE TABLE media_media (
    id UUID PRIMARY KEY,
    report_id UUID NULL,
    owner_id UUID NOT NULL,
    state VARCHAR(16) NOT NULL DEFAULT 'uploaded'
        CHECK (state IN ('uploaded', 'processing', 'ready', 'failed', 'removed')),
    file VARCHAR(255) NOT NULL,
    thumbnail VARCHAR(255) NOT NULL DEFAULT '',
    image_format VARCHAR(16) NOT NULL,
    byte_size INTEGER NOT NULL CHECK (byte_size >= 0),
    width INTEGER NOT NULL CHECK (width >= 0),
    height INTEGER NOT NULL CHECK (height >= 0),
    failure_reason TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT media_media_report_fk
        FOREIGN KEY (report_id) REFERENCES reporting_report(id) ON DELETE RESTRICT,
    CONSTRAINT media_media_owner_fk
        FOREIGN KEY (owner_id) REFERENCES identity_user(id) ON DELETE RESTRICT
);
CREATE TABLE issues_confirmation (
    id UUID PRIMARY KEY,
    issue_id UUID NOT NULL,
    citizen_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT issues_confirmation_one_per_citizen UNIQUE (issue_id, citizen_id),
    CONSTRAINT issues_confirmation_issue_fk
        FOREIGN KEY (issue_id) REFERENCES issues_issue(id) ON DELETE RESTRICT,
    CONSTRAINT issues_confirmation_citizen_fk
        FOREIGN KEY (citizen_id) REFERENCES identity_user(id) ON DELETE RESTRICT
);
CREATE TABLE issues_comment (
    id UUID PRIMARY KEY,
    issue_id UUID NOT NULL,
    author_id UUID NOT NULL,
    body TEXT NOT NULL,
    visibility VARCHAR(16) NOT NULL DEFAULT 'public'
        CHECK (visibility IN ('public', 'internal')),
    moderation_state VARCHAR(16) NOT NULL DEFAULT 'visible'
        CHECK (moderation_state IN ('visible', 'hidden', 'removed')),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    removed_at TIMESTAMPTZ NULL,
    CONSTRAINT issues_comment_issue_fk
        FOREIGN KEY (issue_id) REFERENCES issues_issue(id) ON DELETE RESTRICT,
    CONSTRAINT issues_comment_author_fk
        FOREIGN KEY (author_id) REFERENCES identity_user(id) ON DELETE RESTRICT
);
CREATE TABLE notifications_preference (
    user_id UUID PRIMARY KEY,
    in_app_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    email_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT notification_preference_user_fk
        FOREIGN KEY (user_id) REFERENCES identity_user(id) ON DELETE RESTRICT
);
CREATE TABLE notifications_notification (
    id UUID PRIMARY KEY,
    recipient_id UUID NOT NULL,
    issue_id UUID NOT NULL,
    source_event_id UUID NOT NULL,
    notification_type VARCHAR(50) NOT NULL,
    channel VARCHAR(16) NOT NULL
        CHECK (channel IN ('in_app', 'email', 'sms')),
    body TEXT NOT NULL,
    state VARCHAR(16) NOT NULL DEFAULT 'pending'
        CHECK (state IN ('pending', 'sent', 'delivered', 'failed')),
    sent_at TIMESTAMPTZ NULL,
    delivered_at TIMESTAMPTZ NULL,
    read_at TIMESTAMPTZ NULL,
    failure_reason TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT notification_recipient_fk
        FOREIGN KEY (recipient_id) REFERENCES identity_user(id) ON DELETE RESTRICT,
    CONSTRAINT notification_issue_fk
        FOREIGN KEY (issue_id) REFERENCES issues_issue(id) ON DELETE RESTRICT,
    CONSTRAINT notifications_one_channel_per_event_recipient
        UNIQUE (source_event_id, recipient_id, channel)
);
CREATE TABLE issues_status_event (
    id UUID PRIMARY KEY,
    issue_id UUID NOT NULL,
    actor_id UUID NOT NULL,
    from_status VARCHAR(24) NOT NULL,
    to_status VARCHAR(24) NOT NULL,
    reason TEXT NOT NULL DEFAULT '',
    public_note TEXT NOT NULL DEFAULT '',
    related_issue_id UUID NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT status_event_issue_fk
        FOREIGN KEY (issue_id) REFERENCES issues_issue(id) ON DELETE RESTRICT,
    CONSTRAINT status_event_actor_fk
        FOREIGN KEY (actor_id) REFERENCES identity_user(id) ON DELETE RESTRICT,
    CONSTRAINT status_event_related_issue_fk
        FOREIGN KEY (related_issue_id) REFERENCES issues_issue(id) ON DELETE RESTRICT
);
CREATE TABLE audit_event (
    id UUID PRIMARY KEY,
    actor_id UUID NULL,
    action VARCHAR(96) NOT NULL,
    target_content_type_id INTEGER NOT NULL,
    target_object_id VARCHAR(128) NOT NULL,
    before JSONB NULL,
    after JSONB NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT audit_event_actor_fk
        FOREIGN KEY (actor_id) REFERENCES identity_user(id) ON DELETE RESTRICT,
    CONSTRAINT audit_event_content_type_fk
        FOREIGN KEY (target_content_type_id) REFERENCES django_content_type(id) ON DELETE RESTRICT
);
CREATE TABLE moderation_action (
    id UUID PRIMARY KEY,
    actor_id UUID NOT NULL,
    action VARCHAR(16) NOT NULL CHECK (action IN ('hide', 'remove')),
    reason TEXT NOT NULL,
    target_content_type_id INTEGER NOT NULL,
    target_object_id VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (actor_id) REFERENCES identity_user(id) ON DELETE RESTRICT,
    FOREIGN KEY (target_content_type_id) REFERENCES django_content_type(id) ON DELETE RESTRICT
);
CREATE TABLE notifications_outbox_event (
    id UUID PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id UUID NOT NULL,
    payload JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    last_error TEXT NOT NULL DEFAULT ''
);
ALTER TABLE notifications_notification
    ADD CONSTRAINT notification_source_event_fk
    FOREIGN KEY (source_event_id) REFERENCES notifications_outbox_event(id) ON DELETE RESTRICT;
CREATE TABLE export_export (
    id UUID PRIMARY KEY,
    requester_id UUID NOT NULL,
    resource VARCHAR(16) NOT NULL CHECK (resource IN ('issues', 'reports')),
    format VARCHAR(16) NOT NULL CHECK (format IN ('csv', 'geojson')),
    filters JSONB NOT NULL DEFAULT '{}'::jsonb,
    state VARCHAR(16) NOT NULL DEFAULT 'processing' CHECK (state IN ('processing', 'ready', 'failed')),
    object_key VARCHAR(255) NOT NULL DEFAULT '',
    failure_reason TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NULL,
    FOREIGN KEY (requester_id) REFERENCES identity_user(id) ON DELETE RESTRICT
);
CREATE TABLE identity_password_reset_token (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ NULL,
    attempts SMALLINT NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (user_id) REFERENCES identity_user(id) ON DELETE CASCADE
);
CREATE INDEX identity_user_role_status_idx ON identity_user(role, status);
CREATE INDEX identity_vcode_lookup_idx
    ON identity_verificationcode(user_id, channel, created_at DESC);
CREATE INDEX classification_category_name_en_idx ON classification_category(name_en);
CREATE INDEX classification_category_status_idx ON classification_category(status);
CREATE INDEX classification_kw_status_idx ON classification_severity_keyword(status);
CREATE INDEX geo_city_boundary_active_idx ON geo_city_boundary(is_active);
CREATE INDEX geo_city_boundary_area_gist ON geo_city_boundary USING GIST(area);
CREATE INDEX geo_poi_location_gist ON geo_poi USING GIST(location);
CREATE INDEX geo_poi_type_active_idx ON geo_poi(poi_type, is_active);
CREATE INDEX issues_issue_location_gist ON issues_issue USING GIST(representative_location);
CREATE INDEX issues_issue_queue_idx
    ON issues_issue(primary_category_id, status, opened_at);
CREATE INDEX reporting_report_location_gist ON reporting_report USING GIST(location);
CREATE INDEX reporting_report_author_idx ON reporting_report(author_id, created_at DESC);
CREATE INDEX reporting_report_status_idx ON reporting_report(status, created_at);
CREATE INDEX reporting_report_review_idx ON reporting_report(classification_needs_review);
CREATE INDEX media_media_report_idx ON media_media(report_id, created_at);
CREATE INDEX media_media_unattached_idx
    ON media_media(owner_id, created_at) WHERE report_id IS NULL;
CREATE INDEX issues_comment_issue_created ON issues_comment(issue_id, created_at);
CREATE INDEX notify_recipient_created_idx
    ON notifications_notification(recipient_id, created_at DESC);
CREATE INDEX status_event_issue_idx ON issues_status_event(issue_id, created_at);
CREATE INDEX audit_actor_created_idx ON audit_event(actor_id, created_at);
CREATE INDEX audit_target_idx ON audit_event(target_content_type_id, target_object_id);
CREATE INDEX moderation_action_created_idx ON moderation_action(created_at DESC, id DESC);
CREATE INDEX notify_outbox_pending_idx ON notifications_outbox_event(published_at, occurred_at);
CREATE INDEX notify_outbox_aggregate_idx ON notifications_outbox_event(aggregate_type, aggregate_id);
CREATE INDEX notifications_notification_state_idx ON notifications_notification(state);
CREATE INDEX identity_reset_lookup_idx ON identity_password_reset_token(user_id, created_at DESC);
CREATE INDEX export_export_requester_created_idx ON export_export(requester_id, created_at DESC);
