# Generated by Django 5.2.16 on 2026-08-17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("aggregate_type", models.CharField(max_length=50)),
                ("aggregate_id", models.UUIDField()),
                ("payload", models.JSONField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "outbox event",
                "verbose_name_plural": "outbox events",
                "db_table": "notifications_outbox_event",
                "ordering": ["occurred_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["published_at", "occurred_at"],
                        name="notify_outbox_pending_idx",
                    ),
                    models.Index(
                        fields=["aggregate_type", "aggregate_id"],
                        name="notify_outbox_aggregate_idx",
                    ),
                ],
            },
        ),
    ]
