# Generated by Django 5.2.16 on 2026-08-08 11:56

import django.db.models.deletion
import django.utils.timezone
import urbenmend.media.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('uploaded', 'Uploaded (sanitized, awaiting derivatives)'), ('processing', 'Processing (compression and thumbnail)'), ('ready', 'Ready'), ('failed', 'Processing failed'), ('removed', 'Removed by moderation')], db_index=True, default='uploaded', max_length=16)),
                ('file', models.FileField(max_length=255, upload_to=urbenmend.media.models._upload_path)),
                ('thumbnail', models.FileField(blank=True, max_length=255, upload_to=urbenmend.media.models._thumbnail_path)),
                ('image_format', models.CharField(max_length=16)),
                ('byte_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media', to='reporting.report')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
                'db_table': 'media_media',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['report', 'created_at'], name='media_media_report_idx'), models.Index(condition=models.Q(('report__isnull', True)), fields=['owner', 'created_at'], name='media_media_unattached_idx')],
            },
        ),
    ]
