# Generated by Django 5.2.16 on 2026-08-07 11:15

"""
Authority↔Category scope (T1.5, BR-26).

The M2M `identity.User` ↔ `classification.Category` that A6 deliberately deferred until Category
existed [doc: CLAUDE.md A6, data-model §1 "Authority many ↔ many Category (scope)"].

⚠️ **Purely additive, and none of `0001`'s irreversibility applies.** A new join table plus no
change to `identity_user` — the previous deploy's code, which does not know the relation exists,
runs unchanged against this schema [doc: database.md "backward-compatible migrations only"].

⚠️ **The dependency points identity → classification, not the reverse.** `classification/0001`
names no dependency on `identity` on purpose: the reference-data table stays free of a reference
to the user model, so a future deploy can migrate the taxonomy without the identity app in the
graph.

⚠️ Django generated the `classification.0002_category_slug` dependency rather than `0001` because
the model's `to=` resolves against the latest state. Do not relax it to `0001` — the M2M is keyed
on the Category PK, and the slug migration's `AlterField` step must be settled first.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_category_slug'),
        ('identity', '0002_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category_scope',
            field=models.ManyToManyField(blank=True, help_text='Categories an Authority may view and act on (BR-26). Ignored for other roles.', related_name='scoped_authorities', to='classification.category'),
        ),
    ]
